-- nested queries 
-- the inner query is used for the execution of outer query 

select id, emp_name from empoyees 
where id in (select employee_id from awards);



-- instead of using OR statements we can use IN operator 
select emp_name, department 
from employees where department in ('IT', 'HR', 'Marketing');

-- The equivalent statement for the above query is 
select emp_name, department from employees 
where department = 'IT' or department = 'HR' or department = 'Marketing';


-- The nested query using IN operator
select emp_name from employees 
where employeeID in (select employeeID from Projects where Status = 'Active');
-- The inner query runs give a list of employee id eg(100, 101, 104, 105) 
-- then the outer query gives the ans from the generated list 


-- NOTE:
-- The NOT IN operator checks if a column value in the outer query's result is not present
-- in the inner query's result. The final result will have rows that satisfy the NOT IN condition.

-- Examples 
select StudentName from students 
where StudentName not in ('Alice', 'Bob', 'Charlie');

-- Example in Nested query 
select ProductName from Products 
where ProductID not in (select ProductID from Sales); 
-- The list is generated by the inner query and the outer query's answer will not belong in the generated list (not in)

-- if the inner query gives NULL then the inner query gives a unknown state 
-- => so sql doesnt know what is not in NULL 
-- so the correct query is 
select EmpName from Employees 
where EmpName not in (select ManagerName from Managers where ManagerName is not null);
-- we add a extra WHERE condition saying that the inner query's result will be not null 


-- ALL operator 
-- ALL requires your condition to be true against every single value returned by the subquery

-- VERY IMPORTANT diff of ALL and ANY
-- > ALL (10, 20, 30): Means the value must be greater than 10 AND greater than 20 AND greater than 30.
-- > ANY (10, 20, 30): Means the value must be greater than 10 OR 20 OR 30

-- example:
select ProductName, Price from Products 
where Price > ALL (select Price from products where category = 'Basic');
-- the list of all prices that the inner query gives then the outer query must staisfy all the prices returned by inner query 

